version: '3'
services:
  mysql:
    image: percona/percona-server:8.0
    ports:
       - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: mypassword

  
  app_server1:
    image: html-server:1.0
    ports: 
       - 8081:80
    links:
       - mysql:mysql
    depends_on:
       - mysql

  app_server2:
    image: html-server:1.0      
    ports:
       - 8082:80
    links:
       - mysql:mysql
    depends_on:
       - mysql
 
  nginx:
    image: load-balancer:1.0
    ports:
       - 8080:80
    depends_on:
       - mysql
       - app_server1
       - app_server2  
